version: '3.9'

services:
  tasked:
    build:
      context: .
      args:
        HTTP_PROXY:
        HTTPS_PROXY:
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - data:/app/data/

volumes:
  data:
